name = "WhiteMagicResonance"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["WhiteMagic Core <core@whitemagic.ai>"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
